import { registerConcept } from "@mit-sdg/sync-engine/assembly";
import spec from "@design/concepts/Agreeing.md" with { type: "text" };
import {
  AcceptanceExpired,
  AcceptanceNotAuthorized,
  AcceptanceNotPending,
  AcceptanceStaleVersion,
  AgreeingConcept,
  ProposalInvalidDeadline,
  ProposalInvalidTerms,
  ProposalSameParticipant,
  RejectionNotAuthorized,
  RejectionNotPending,
  RejectionStaleVersion,
  RevisionExpired,
  RevisionInvalidDeadline,
  RevisionInvalidTerms,
  RevisionNotParticipant,
  RevisionNotPending,
  RevisionStaleVersion,
  RevisionUnchanged,
  WithdrawalNotAuthorized,
  WithdrawalNotPending,
  WithdrawalStaleVersion,
} from "./Agreeing.ts";

export const agreeing = registerConcept({
  class: AgreeingConcept,
  spec,
  refusals: {
    PROPOSAL_SAME_PARTICIPANT: ProposalSameParticipant,
    PROPOSAL_INVALID_TERMS: ProposalInvalidTerms,
    PROPOSAL_INVALID_DEADLINE: ProposalInvalidDeadline,
    REVISION_NOT_PENDING: RevisionNotPending,
    REVISION_NOT_PARTICIPANT: RevisionNotParticipant,
    REVISION_STALE_VERSION: RevisionStaleVersion,
    REVISION_EXPIRED: RevisionExpired,
    REVISION_INVALID_TERMS: RevisionInvalidTerms,
    REVISION_INVALID_DEADLINE: RevisionInvalidDeadline,
    REVISION_UNCHANGED: RevisionUnchanged,
    ACCEPTANCE_NOT_PENDING: AcceptanceNotPending,
    ACCEPTANCE_STALE_VERSION: AcceptanceStaleVersion,
    ACCEPTANCE_NOT_AUTHORIZED: AcceptanceNotAuthorized,
    ACCEPTANCE_EXPIRED: AcceptanceExpired,
    REJECTION_NOT_PENDING: RejectionNotPending,
    REJECTION_STALE_VERSION: RejectionStaleVersion,
    REJECTION_NOT_AUTHORIZED: RejectionNotAuthorized,
    WITHDRAWAL_NOT_PENDING: WithdrawalNotPending,
    WITHDRAWAL_STALE_VERSION: WithdrawalStaleVersion,
    WITHDRAWAL_NOT_AUTHORIZED: WithdrawalNotAuthorized,
  },
});
