import { httpPolicy } from "@mit-sdg/sync-engine-http/policy";

export const policy = httpPolicy({
  basePath: "/api",
  publicErrors: {
    INVALID_CREDENTIALS: "INVALID_REQUEST",
    USERNAME_TAKEN: "CONFLICT",
    UNKNOWN_SESSION: "UNAUTHORIZED",
    PROPOSAL_SAME_PARTICIPANT: "INVALID_REQUEST",
    PROPOSAL_INVALID_TERMS: "INVALID_REQUEST",
    PROPOSAL_INVALID_DEADLINE: "INVALID_REQUEST",
    ACCEPTANCE_NOT_PENDING: "INVALID_REQUEST",
    ACCEPTANCE_STALE_VERSION: "INVALID_REQUEST",
    ACCEPTANCE_NOT_AUTHORIZED: "FORBIDDEN",
    ACCEPTANCE_EXPIRED: "INVALID_REQUEST",
  },
});
